#!/usr/bin/env node

/**
 * Build Script for JSON Schema to TypeScript Generation
 *
 * Converts all JSON schemas in shared/schemas to TypeScript types
 * Output: shared/types/protocol.ts
 */

const { compileFromFile } = require('json-schema-to-typescript');
const fs = require('fs');
const path = require('path');
const { glob } = require('glob');

const SCHEMAS_DIR = path.join(__dirname, '../shared/schemas');
const OUTPUT_FILE = path.join(__dirname, '../shared/types/protocol.ts');

async function buildSchemas() {
  console.log('🔨 Building TypeScript types from JSON schemas...\n');

  try {
    // Ensure output directory exists
    const outputDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Find all JSON schema files
    const schemaFiles = glob.sync(`${SCHEMAS_DIR}/**/*.json`);

    if (schemaFiles.length === 0) {
      console.warn('⚠️  No schema files found in', SCHEMAS_DIR);
      return;
    }

    console.log(`📋 Found ${schemaFiles.length} schema files:\n`);

    // Compile each schema file
    let allTypes = [];
    allTypes.push('/* eslint-disable */');
    allTypes.push('/**');
    allTypes.push(' * AUTO-GENERATED FILE - DO NOT EDIT');
    allTypes.push(' * Generated by: npm run build:schemas');
    allTypes.push(' * Source: shared/schemas/**/*.json');
    allTypes.push(' * Date: ' + new Date().toISOString());
    allTypes.push(' */');
    allTypes.push('');

    for (const schemaFile of schemaFiles) {
      const relativePath = path.relative(SCHEMAS_DIR, schemaFile);
      console.log(`  ✓ Processing: ${relativePath}`);

      try {
        const ts = await compileFromFile(schemaFile, {
          bannerComment: '',
          style: {
            semi: true,
            singleQuote: true,
            trailingComma: 'es5',
          },
          unreachableDefinitions: false,
          enableConstEnums: true,
        });

        // Remove duplicate header comments
        const cleanTs = ts
          .replace(/^\/\* eslint-disable \*\/\n/gm, '')
          .replace(/^\/\*\*[\s\S]*?\*\/\n/gm, '')
          .trim();

        allTypes.push(`// ${relativePath}`);
        allTypes.push(cleanTs);
        allTypes.push('');
      } catch (error) {
        console.error(`  ✗ Error processing ${relativePath}:`, error.message);
      }
    }

    // Write output file
    const output = allTypes.join('\n');
    fs.writeFileSync(OUTPUT_FILE, output, 'utf8');

    console.log(`\n✅ Successfully generated TypeScript types!`);
    console.log(`📄 Output: ${path.relative(process.cwd(), OUTPUT_FILE)}`);
    console.log(`📊 Size: ${(output.length / 1024).toFixed(2)} KB\n`);

  } catch (error) {
    console.error('\n❌ Build failed:', error.message);
    console.error(error.stack);
    process.exit(1);
  }
}

// Run the build
buildSchemas().catch((error) => {
  console.error('❌ Unexpected error:', error);
  process.exit(1);
});
