target_sources(ZenithDAW PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/MainWindow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/MainLayoutComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/SampleEditorComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/arranger/ArrangerComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/arranger/ArrangerTrackComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/mixer/MixerComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/piano-roll/PianoRollComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/session/DrumPadComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/arranger/AutomationLaneComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/arranger/MarkerLaneComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/arranger/TempoLaneComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/browser/PluginBrowserComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/arranger/ClipComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/mixer/MixerView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/mixer/MixerChannelComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/arranger/TrackHeaderComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/arranger/TimelineRuler.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/PluginEditorWindow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/browser/PresetBrowserComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/browser/InstrumentBrowserPanel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/WingmanPanel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/AudioFeedback.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/design-system/ZenithLookAndFeel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/design-system/ZenithTheme.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/ZenithHubComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/RefactorPanel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/LayoutManager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/ResizablePanelContainer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/session/SessionViewComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/MacroToolbar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/arranger/MiniMapComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/views/SpectraAnalyzerComponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/piano-roll/ModulationMatrixView.cpp
)

add_subdirectory(skia)