# CMake generated Testfile for 
# Source directory: C:/zenith/daw/modules/zenith-core
# Build directory: C:/zenith/daw/build_skia/modules/zenith-core
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[ProjectStateTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/ProjectStateTests_artefacts/Debug/ProjectStateTests.exe")
  set_tests_properties([=[ProjectStateTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;344;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[ProjectStateTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/ProjectStateTests_artefacts/Release/ProjectStateTests.exe")
  set_tests_properties([=[ProjectStateTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;344;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[ProjectStateTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/ProjectStateTests_artefacts/MinSizeRel/ProjectStateTests.exe")
  set_tests_properties([=[ProjectStateTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;344;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[ProjectStateTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/ProjectStateTests_artefacts/RelWithDebInfo/ProjectStateTests.exe")
  set_tests_properties([=[ProjectStateTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;344;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
else()
  add_test([=[ProjectStateTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[TempoTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/TempoTests_artefacts/Debug/TempoTests.exe")
  set_tests_properties([=[TempoTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;373;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[TempoTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/TempoTests_artefacts/Release/TempoTests.exe")
  set_tests_properties([=[TempoTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;373;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[TempoTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/TempoTests_artefacts/MinSizeRel/TempoTests.exe")
  set_tests_properties([=[TempoTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;373;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[TempoTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/TempoTests_artefacts/RelWithDebInfo/TempoTests.exe")
  set_tests_properties([=[TempoTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;373;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
else()
  add_test([=[TempoTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[RecordingAutomationTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/RecordingAutomationTests_artefacts/Debug/RecordingAutomationTests.exe")
  set_tests_properties([=[RecordingAutomationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;409;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[RecordingAutomationTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/RecordingAutomationTests_artefacts/Release/RecordingAutomationTests.exe")
  set_tests_properties([=[RecordingAutomationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;409;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[RecordingAutomationTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/RecordingAutomationTests_artefacts/MinSizeRel/RecordingAutomationTests.exe")
  set_tests_properties([=[RecordingAutomationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;409;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[RecordingAutomationTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/RecordingAutomationTests_artefacts/RelWithDebInfo/RecordingAutomationTests.exe")
  set_tests_properties([=[RecordingAutomationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;409;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
else()
  add_test([=[RecordingAutomationTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[InstrumentValidationTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/InstrumentValidationTests_artefacts/Debug/InstrumentValidationTests.exe")
  set_tests_properties([=[InstrumentValidationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;459;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[InstrumentValidationTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/InstrumentValidationTests_artefacts/Release/InstrumentValidationTests.exe")
  set_tests_properties([=[InstrumentValidationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;459;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[InstrumentValidationTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/InstrumentValidationTests_artefacts/MinSizeRel/InstrumentValidationTests.exe")
  set_tests_properties([=[InstrumentValidationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;459;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[InstrumentValidationTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/InstrumentValidationTests_artefacts/RelWithDebInfo/InstrumentValidationTests.exe")
  set_tests_properties([=[InstrumentValidationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;459;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
else()
  add_test([=[InstrumentValidationTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[PresetRegressionTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/PresetRegressionTests_artefacts/Debug/PresetRegressionTests.exe")
  set_tests_properties([=[PresetRegressionTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;509;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[PresetRegressionTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/PresetRegressionTests_artefacts/Release/PresetRegressionTests.exe")
  set_tests_properties([=[PresetRegressionTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;509;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[PresetRegressionTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/PresetRegressionTests_artefacts/MinSizeRel/PresetRegressionTests.exe")
  set_tests_properties([=[PresetRegressionTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;509;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[PresetRegressionTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/PresetRegressionTests_artefacts/RelWithDebInfo/PresetRegressionTests.exe")
  set_tests_properties([=[PresetRegressionTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;509;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
else()
  add_test([=[PresetRegressionTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[TrackInstrumentIntegrationTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/TrackInstrumentIntegrationTests_artefacts/Debug/TrackInstrumentIntegrationTests.exe")
  set_tests_properties([=[TrackInstrumentIntegrationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;595;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[TrackInstrumentIntegrationTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/TrackInstrumentIntegrationTests_artefacts/Release/TrackInstrumentIntegrationTests.exe")
  set_tests_properties([=[TrackInstrumentIntegrationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;595;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[TrackInstrumentIntegrationTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/TrackInstrumentIntegrationTests_artefacts/MinSizeRel/TrackInstrumentIntegrationTests.exe")
  set_tests_properties([=[TrackInstrumentIntegrationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;595;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[TrackInstrumentIntegrationTests]=] "C:/zenith/daw/build_skia/modules/zenith-core/TrackInstrumentIntegrationTests_artefacts/RelWithDebInfo/TrackInstrumentIntegrationTests.exe")
  set_tests_properties([=[TrackInstrumentIntegrationTests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;595;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
else()
  add_test([=[TrackInstrumentIntegrationTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SkiaSimpleTest]=] "C:/zenith/daw/build_skia/modules/zenith-core/SkiaSimpleTest_artefacts/Debug/SkiaSimpleTest.exe")
  set_tests_properties([=[SkiaSimpleTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;628;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SkiaSimpleTest]=] "C:/zenith/daw/build_skia/modules/zenith-core/SkiaSimpleTest_artefacts/Release/SkiaSimpleTest.exe")
  set_tests_properties([=[SkiaSimpleTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;628;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SkiaSimpleTest]=] "C:/zenith/daw/build_skia/modules/zenith-core/SkiaSimpleTest_artefacts/MinSizeRel/SkiaSimpleTest.exe")
  set_tests_properties([=[SkiaSimpleTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;628;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SkiaSimpleTest]=] "C:/zenith/daw/build_skia/modules/zenith-core/SkiaSimpleTest_artefacts/RelWithDebInfo/SkiaSimpleTest.exe")
  set_tests_properties([=[SkiaSimpleTest]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/zenith/daw/modules/zenith-core/CMakeLists.txt;628;add_test;C:/zenith/daw/modules/zenith-core/CMakeLists.txt;0;")
else()
  add_test([=[SkiaSimpleTest]=] NOT_AVAILABLE)
endif()
subdirs("../../_deps/juce-build")
