/* eslint-disable */
/**
 * AUTO-GENERATED PROTOCOL TYPES
 *
 * This file contains TypeScript type definitions for the Zenith DAW protocol.
 * It serves as the single source of truth for all command/event schemas.
 *
 * DO NOT EDIT THIS FILE MANUALLY - regenerate with: npm run build:schemas
 *
 * Source: shared/schemas/**/*.json
 * Generated: 2025-11-10
 */

// =============================================================================
// UUID Type
// =============================================================================

/** UUID v4 string (RFC 4122) */
export type UUID = string;

// =============================================================================
// TRANSPORT COMMANDS
// =============================================================================

export interface TransportPlayCommand {
  command: 'transport_play';
  params: Record<string, never>;
}

export interface TransportStopCommand {
  command: 'transport_stop';
  params: {
    returnToStart?: boolean;
  };
}

export interface TransportSetPositionCommand {
  command: 'transport_set_position';
  params: {
    beat: number;
  };
}

export interface TransportRecordCommand {
  command: 'transport_record';
  params: Record<string, never>;
}

export interface SetTempoCommand {
  command: 'set_tempo';
  params: {
    tempo: number; // 1-999 BPM
    beat?: number;
  };
}

export interface SetTimeSignatureCommand {
  command: 'set_time_signature';
  params: {
    numerator: number; // 1-64
    denominator: 1 | 2 | 4 | 8 | 16 | 32;
    beat?: number;
  };
}

// =============================================================================
// TRACK COMMANDS
// =============================================================================

export type TrackType = 'audio' | 'midi' | 'instrument' | 'bus' | 'master';

export interface CreateTrackCommand {
  command: 'create_track';
  params: {
    type: TrackType;
    name: string;
    position?: number;
  };
}

export interface DeleteTrackCommand {
  command: 'delete_track';
  params: {
    trackId: UUID;
  };
}

export interface SetTrackPropertiesCommand {
  command: 'set_track_properties';
  params: {
    trackId: UUID;
    properties: {
      name?: string;
      volumeDb?: number; // -120 to +12
      pan?: number; // -1.0 to +1.0
      muted?: boolean;
      solo?: boolean;
      armed?: boolean;
      color?: string; // Hex color
    };
  };
}

export interface ReorderTracksCommand {
  command: 'reorder_tracks';
  params: {
    trackId: UUID;
    newPosition: number;
  };
}

// =============================================================================
// CLIP COMMANDS
// =============================================================================

export type ClipType = 'audio' | 'midi';

export interface MidiNote {
  startBeat: number;
  lengthBeats: number;
  pitch: number; // 0-127
  velocity: number; // 1-127
}

export interface CreateMidiClipCommand {
  command: 'create_midi_clip';
  params: {
    trackId: UUID;
    startBeat: number;
    lengthBeats: number;
    name?: string;
  };
}

export interface SetClipNotesCommand {
  command: 'set_clip_notes';
  params: {
    clipId: UUID;
    notes: MidiNote[];
  };
}

export interface LoadAudioClipCommand {
  command: 'load_audio_clip';
  params: {
    trackId: UUID;
    audioFileId: UUID;
    startBeat: number;
    name?: string;
  };
}

export interface SetClipPropertiesCommand {
  command: 'set_clip_properties';
  params: {
    clipId: UUID;
    properties: {
      name?: string;
      startBeat?: number;
      lengthBeats?: number;
      muted?: boolean;
      color?: string;
      // Audio-specific properties
      fadeInBeats?: number;
      fadeOutBeats?: number;
      gain?: number; // 0.0 to 2.0
      playbackRate?: number; // 0.25 to 4.0
      pitchShift?: number; // -12 to +12
    };
  };
}

export interface DeleteClipCommand {
  command: 'delete_clip';
  params: {
    clipId: UUID;
  };
}

// =============================================================================
// PLUGIN COMMANDS
// =============================================================================

export interface InsertPluginCommand {
  command: 'insert_plugin';
  params: {
    trackId: UUID;
    pluginId: string;
    position?: number;
  };
}

export interface RemovePluginCommand {
  command: 'remove_plugin';
  params: {
    trackId: UUID;
    pluginSlotId: UUID;
  };
}

export interface SetPluginParamCommand {
  command: 'set_plugin_param';
  params: {
    pluginSlotId: UUID;
    parameterId: string;
    value: number; // 0.0 to 1.0 (normalized)
  };
}

// =============================================================================
// PROJECT COMMANDS
// =============================================================================

export type ProjectFormat = 'json' | 'binary';

export interface SaveProjectCommand {
  command: 'save_project';
  params: {
    path: string;
    format?: ProjectFormat;
  };
}

export interface LoadProjectCommand {
  command: 'load_project';
  params: {
    path: string;
  };
}

export interface NewProjectCommand {
  command: 'new_project';
  params: {
    name: string;
    sampleRate?: 44100 | 48000 | 88200 | 96000 | 176400 | 192000;
    bitDepth?: 16 | 24 | 32;
  };
}

// =============================================================================
// COMMAND UNION TYPE
// =============================================================================

export type Command =
  | TransportPlayCommand
  | TransportStopCommand
  | TransportSetPositionCommand
  | TransportRecordCommand
  | SetTempoCommand
  | SetTimeSignatureCommand
  | CreateTrackCommand
  | DeleteTrackCommand
  | SetTrackPropertiesCommand
  | ReorderTracksCommand
  | CreateMidiClipCommand
  | SetClipNotesCommand
  | LoadAudioClipCommand
  | SetClipPropertiesCommand
  | DeleteClipCommand
  | InsertPluginCommand
  | RemovePluginCommand
  | SetPluginParamCommand
  | SaveProjectCommand
  | LoadProjectCommand
  | NewProjectCommand;

// =============================================================================
// TRANSPORT EVENTS
// =============================================================================

export interface TimeSignature {
  numerator: number;
  denominator: 1 | 2 | 4 | 8 | 16 | 32;
}

export interface TransportStateEvent {
  type: 'transport_state';
  timestamp: string; // ISO 8601
  data: {
    isPlaying: boolean;
    isRecording: boolean;
    position: number; // beats
    tempo: number; // BPM
    timeSignature: TimeSignature;
  };
}

export interface PlayheadPositionEvent {
  type: 'playhead_position';
  timestamp: string;
  data: {
    beat: number;
    bar: number;
    beatInBar: number;
    sample: number;
  };
}

// =============================================================================
// TRACK EVENTS
// =============================================================================

export interface Track {
  id: UUID;
  name: string;
  type: TrackType;
  order: number;
  volumeDb: number;
  pan: number;
  muted: boolean;
  solo: boolean;
  armed: boolean;
  color: string;
  [key: string]: any; // Allow additional properties
}

export interface TrackAddedEvent {
  type: 'track_added';
  timestamp: string;
  data: {
    track: Track;
  };
}

export interface TrackUpdatedEvent {
  type: 'track_updated';
  timestamp: string;
  data: {
    trackId: UUID;
    changes: Record<string, any>;
  };
}

export interface TrackRemovedEvent {
  type: 'track_removed';
  timestamp: string;
  data: {
    trackId: UUID;
  };
}

// =============================================================================
// CLIP EVENTS
// =============================================================================

export interface Clip {
  id: UUID;
  trackId: UUID;
  type: ClipType;
  name: string;
  startBeat: number;
  lengthBeats: number;
  [key: string]: any; // Allow additional properties
}

export interface ClipAddedEvent {
  type: 'clip_added';
  timestamp: string;
  data: {
    clip: Clip;
  };
}

export interface ClipUpdatedEvent {
  type: 'clip_updated';
  timestamp: string;
  data: {
    clipId: UUID;
    changes: Record<string, any>;
  };
}

export interface ClipRemovedEvent {
  type: 'clip_removed';
  timestamp: string;
  data: {
    clipId: UUID;
    trackId: UUID;
  };
}

// =============================================================================
// PLUGIN EVENTS
// =============================================================================

export interface PluginSlot {
  id: UUID;
  pluginId: string;
  pluginName: string;
  trackId?: UUID;
  [key: string]: any;
}

export interface PluginInsertedEvent {
  type: 'plugin_inserted';
  timestamp: string;
  data: {
    pluginSlot: PluginSlot;
  };
}

export interface PluginParamChangedEvent {
  type: 'plugin_param_changed';
  timestamp: string;
  data: {
    pluginSlotId: UUID;
    parameterId: string;
    value: number;
    displayValue?: string;
  };
}

export interface PluginRemovedEvent {
  type: 'plugin_removed';
  timestamp: string;
  data: {
    pluginSlotId: UUID;
    trackId: UUID;
  };
}

// =============================================================================
// METERING EVENTS
// =============================================================================

export interface MeterValues {
  peak: number[]; // dB per channel
  rms: number[]; // dB per channel
}

export interface MetersEvent {
  type: 'meters';
  timestamp: string;
  data: {
    tracks: Record<UUID, MeterValues>;
    master: MeterValues;
  };
}

// =============================================================================
// PROJECT EVENTS
// =============================================================================

export interface Project {
  id: UUID;
  name: string;
  version: string; // semver
  sampleRate: 44100 | 48000 | 88200 | 96000 | 176400 | 192000;
  bitDepth: 16 | 24 | 32;
  [key: string]: any;
}

export interface ProjectStateEvent {
  type: 'project_state';
  timestamp: string;
  data: {
    project: Project;
  };
}

// =============================================================================
// EVENT UNION TYPE
// =============================================================================

export type Event =
  | TransportStateEvent
  | PlayheadPositionEvent
  | TrackAddedEvent
  | TrackUpdatedEvent
  | TrackRemovedEvent
  | ClipAddedEvent
  | ClipUpdatedEvent
  | ClipRemovedEvent
  | PluginInsertedEvent
  | PluginParamChangedEvent
  | PluginRemovedEvent
  | MetersEvent
  | ProjectStateEvent;

// =============================================================================
// COMMAND/EVENT MESSAGE WRAPPERS
// =============================================================================

export interface CommandRequest<T extends Command = Command> {
  id: UUID; // Request ID for tracking
  command: T['command'];
  params: T['params'];
}

export interface CommandResponse<T = any> {
  id: UUID; // Matches request ID
  success: boolean;
  result?: T;
  error?: CommandError;
}

export interface CommandError {
  code: ErrorCode;
  message: string;
  details?: Record<string, any>;
}

export type ErrorCode =
  | 'INVALID_PARAM'
  | 'NOT_FOUND'
  | 'PERMISSION_DENIED'
  | 'RESOURCE_BUSY'
  | 'AUDIO_ERROR'
  | 'IO_ERROR'
  | 'PLUGIN_ERROR'
  | 'UNKNOWN_ERROR';

// =============================================================================
// TYPE GUARDS
// =============================================================================

export function isCommand(obj: any): obj is Command {
  return obj && typeof obj === 'object' && 'command' in obj && 'params' in obj;
}

export function isEvent(obj: any): obj is Event {
  return obj && typeof obj === 'object' && 'type' in obj && 'timestamp' in obj && 'data' in obj;
}

export function isCommandRequest(obj: any): obj is CommandRequest {
  return obj && typeof obj === 'object' && 'id' in obj && 'command' in obj && 'params' in obj;
}

export function isCommandResponse(obj: any): obj is CommandResponse {
  return obj && typeof obj === 'object' && 'id' in obj && 'success' in obj;
}

// =============================================================================
// UTILITY TYPES
// =============================================================================

/** Extract the command name from a Command type */
export type CommandName = Command['command'];

/** Extract the event type from an Event type */
export type EventType = Event['type'];

/** Get command type by name */
export type CommandByName<T extends CommandName> = Extract<Command, { command: T }>;

/** Get event type by name */
export type EventByType<T extends EventType> = Extract<Event, { type: T }>;
