#!/usr/bin/env python3
"""Generate Zenith's baked font modules (font_*.zig) from a modern typeface.

Renders ASCII 32..126 with 3x supersampling for clean grayscale AA, packed in
the existing Font format (cell_h, first=32, subpixel layout = coverage
replicated to R,G,B so the CPU path shows no color fringe and the GPU atlas
averages back to the same coverage).
"""
from PIL import Image, ImageFont, ImageDraw

SS = 3
FIRST, LAST = 32, 126


def gen(otf, size):
    font = ImageFont.truetype(otf, size)
    font_ss = ImageFont.truetype(otf, size * SS)
    ascent, descent = font.getmetrics()
    cell_h = ascent + descent
    advances, widths, offsets, data = [], [], [], bytearray()
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        adv = round(font.getlength(ch))
        if adv < 1:
            adv = max(1, round(size * 0.3))
        w = adv
        offsets.append(len(data))
        img = Image.new("L", (max(w * SS, 1), cell_h * SS), 0)
        ImageDraw.Draw(img).text((0, 0), ch, font=font_ss, fill=255)
        img = img.resize((max(w, 1), cell_h), Image.LANCZOS)
        px = img.load()
        for gy in range(cell_h):
            for gx in range(w):
                c = px[gx, gy]
                data += bytes((c, c, c))
        advances.append(adv)
        widths.append(w)
    return cell_h, advances, widths, offsets, data


def emit(path, cell_h, adv, wid, off, data, label):
    def arr(name, vals, ty):
        return f"const {name}=[_]{ty}{{" + ",".join(str(v) for v in vals) + "};\n"
    with open(path, "w") as f:
        f.write(f"//! Generated by tools/genfont.py — {label}. Subpixel-replicated grayscale AA.\n")
        f.write('const Font=@import("font.zig").Font;\n')
        f.write(arr("advance_a", adv, "u8"))
        f.write(arr("width_a", wid, "u8"))
        f.write(arr("offset_a", off, "u32"))
        f.write(arr("data_a", list(data), "u8"))
        f.write(f"pub const font=Font{{.cell_h={cell_h},.first=32,.subpixel=true,.advance=&advance_a,.width=&width_a,.offset=&offset_a,.data=&data_a}};\n")


FIRA = "/usr/share/fonts/opentype/fira/"
JOBS = [
    ("zig/font_body.zig", FIRA + "FiraSans-Regular.otf", 14, "Fira Sans Regular 14"),
    ("zig/font_ui.zig", FIRA + "FiraSans-Medium.otf", 16, "Fira Sans Medium 16"),
    ("zig/font_display.zig", FIRA + "FiraSans-SemiBold.otf", 24, "Fira Sans SemiBold 24"),
]
for path, otf, size, label in JOBS:
    ch, a, w, o, d = gen(otf, size)
    emit(path, ch, a, w, o, d, label)
    print(f"{path}: cell_h={ch}, glyphs={len(a)}, data={len(d)//1024}KB")
