//! genfont.zig — regenerate a font_*.zig baked module from a .ttf file.
//! Replaces tools/genfont.py.
//!
//! Usage:
//!   zig build genfont -- --font /usr/share/fonts/opentype/fira/FiraSans-Regular.otf \
//!                        --size 14 --name "Fira Sans Regular" --out zig/font_ui.zig
//!
//! The output matches the format that font.zig and gpu2d.zig consume:
//!   const advance_a=[_]u8{...};
//!   const bitmap_a=[_]u8{...};
//!   pub const font: Font = .{ ... };

const std = @import("std");
const ttf = @import("ttf");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    const args = try std.process.argsAlloc(alloc);
    defer std.process.argsFree(alloc, args);

    var font_path: []const u8 = "";
    var size: f32 = 14.0;
    var name: []const u8 = "";
    var out_path: []const u8 = "";

    var i: usize = 1;
    while (i < args.len) : (i += 1) {
        if (std.mem.eql(u8, args[i], "--font") and i + 1 < args.len) {
            i += 1;
            font_path = args[i];
        } else if (std.mem.eql(u8, args[i], "--size") and i + 1 < args.len) {
            i += 1;
            size = std.fmt.parseFloat(f32, args[i]) catch {
                try std.io.getStdErr().writer().print("Bad --size: {s}\n", .{args[i]});
                std.process.exit(1);
            };
        } else if (std.mem.eql(u8, args[i], "--name") and i + 1 < args.len) {
            i += 1;
            name = args[i];
        } else if (std.mem.eql(u8, args[i], "--out") and i + 1 < args.len) {
            i += 1;
            out_path = args[i];
        }
    }

    if (font_path.len == 0 or out_path.len == 0) {
        try std.io.getStdErr().writer().writeAll(
            "Usage: genfont --font <path.ttf> --size <px> [--name <display>] --out <path.zig>\n",
        );
        std.process.exit(1);
    }
    if (name.len == 0) {
        name = std.fs.path.stem(std.fs.path.basename(font_path));
    }

    const ttf_bytes = std.fs.cwd().readFileAlloc(alloc, font_path, 64 * 1024 * 1024) catch |e| {
        try std.io.getStdErr().writer().print("Cannot read {s}: {}\n", .{ font_path, e });
        std.process.exit(1);
    };
    defer alloc.free(ttf_bytes);

    const font = ttf.rasterizeAscii(alloc, ttf_bytes, size) catch |e| {
        try std.io.getStdErr().writer().print("TTF rasterize failed: {}\n", .{e});
        std.process.exit(1);
    };
    defer ttf.freeFont(alloc, font);

    var out = std.ArrayList(u8).init(alloc);
    defer out.deinit();
    const w = out.writer();

    try w.print("//! Generated by tools/genfont.zig — {s} {d}px.\n", .{ name, @as(u32, @intFromFloat(size)) });
    try w.writeAll("const Font=@import(\"font.zig\").Font;\n");

    try writeU8Array(w, "advance_a", font.advance);
    try writeU8Array(w, "width_a", font.width);
    try writeU32Array(w, "offset_a", font.offset);
    try writeU8Array(w, "bitmap_a", font.data);

    try w.print(
        "pub const font: Font = .{{" ++
            ".cell_h={d},.first=32,.subpixel={}," ++
            ".advance=&advance_a,.width=&width_a,.offset=&offset_a,.data=&bitmap_a}};\n",
        .{ font.cell_h, font.subpixel },
    );

    try std.fs.cwd().writeFile(.{ .sub_path = out_path, .data = out.items });

    try std.io.getStdOut().writer().print(
        "Wrote {d} bytes to {s} ({d} chars, cell_h={d})\n",
        .{ out.items.len, out_path, font.advance.len, font.cell_h },
    );
}

fn writeU8Array(w: anytype, name: []const u8, data: []const u8) !void {
    try w.print("const {s}=[_]u8{{", .{name});
    for (data, 0..) |v, j| {
        if (j > 0) try w.writeByte(',');
        try w.print("{d}", .{v});
    }
    try w.writeAll("};\n");
}

fn writeU32Array(w: anytype, name: []const u8, data: []const u32) !void {
    try w.print("const {s}=[_]u32{{", .{name});
    for (data, 0..) |v, j| {
        if (j > 0) try w.writeByte(',');
        try w.print("{d}", .{v});
    }
    try w.writeAll("};\n");
}
